-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.8.0
-- Generated: 2022-04-13 22:24 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_torrelabs_candidate_summary_context_2 (
    "schema_vendor"       VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_name"         VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_format"       VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_version"      VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "root_id"             CHAR(36)         ENCODE RAW       NOT NULL,
    "root_tstamp"         TIMESTAMP        ENCODE ZSTD      NOT NULL,
    "ref_root"            VARCHAR(255)     ENCODE ZSTD      NOT NULL,
    "ref_tree"            VARCHAR(1500)    ENCODE ZSTD      NOT NULL,
    "ref_parent"          VARCHAR(255)     ENCODE ZSTD      NOT NULL,
    "column_id"           VARCHAR(50)      ENCODE ZSTD,
    "column_last_updated" VARCHAR(250)     ENCODE ZSTD,
    "id"                  VARCHAR(50)      ENCODE ZSTD,
    "interested"          VARCHAR(200)     ENCODE ZSTD,
    "position"            DOUBLE PRECISION ENCODE RAW,
    "pre_matched"         BOOLEAN          ENCODE RUNLENGTH,
    "public_application"  BOOLEAN          ENCODE RUNLENGTH,
    "retracted"           VARCHAR(200)     ENCODE ZSTD,
    "reviewed"            VARCHAR(200)     ENCODE ZSTD,
    "reviewed_from"       VARCHAR(200)     ENCODE ZSTD,
    "stage"               VARCHAR(200)     ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_torrelabs_candidate_summary_context_2 IS 'iglu:com.torrelabs/CandidateSummaryContext/jsonschema/2-0-0';
