-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.8.0
-- Generated: 2022-04-13 22:24 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_torrelabs_discovery_search_performance_1 (
    "schema_vendor"             VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_name"               VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_format"             VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_version"            VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "root_id"                   CHAR(36)         ENCODE RAW       NOT NULL,
    "root_tstamp"               TIMESTAMP        ENCODE ZSTD      NOT NULL,
    "ref_root"                  VARCHAR(255)     ENCODE ZSTD      NOT NULL,
    "ref_tree"                  VARCHAR(1500)    ENCODE ZSTD      NOT NULL,
    "ref_parent"                VARCHAR(255)     ENCODE ZSTD      NOT NULL,
    "search_id"                 VARCHAR(255)     ENCODE ZSTD      NOT NULL,
    "aggregations"              BOOLEAN          ENCODE RUNLENGTH,
    "event_text"                VARCHAR(255)     ENCODE ZSTD,
    "filter_compensation"       VARCHAR(255)     ENCODE ZSTD,
    "filter_compensation_range" VARCHAR(255)     ENCODE ZSTD,
    "filter_job"                VARCHAR(255)     ENCODE ZSTD,
    "filter_languages"          VARCHAR(255)     ENCODE ZSTD,
    "filter_location"           VARCHAR(255)     ENCODE ZSTD,
    "filter_name"               VARCHAR(255)     ENCODE ZSTD,
    "filter_opportunity_type"   VARCHAR(255)     ENCODE ZSTD,
    "filter_organization"       VARCHAR(255)     ENCODE ZSTD,
    "filter_remoter"            VARCHAR(255)     ENCODE ZSTD,
    "filter_role"               VARCHAR(255)     ENCODE ZSTD,
    "filter_signaled_by"        VARCHAR(255)     ENCODE ZSTD,
    "filter_signalers_of"       VARCHAR(255)     ENCODE ZSTD,
    "filter_skill"              VARCHAR(255)     ENCODE ZSTD,
    "filter_skill_role"         VARCHAR(255)     ENCODE ZSTD,
    "response_time"             DOUBLE PRECISION ENCODE RAW,
    "results"                   INT              ENCODE ZSTD,
    "search_session_id"         VARCHAR(255)     ENCODE ZSTD,
    "search_target"             VARCHAR(255)     ENCODE ZSTD,
    "send_at"                   VARCHAR(255)     ENCODE ZSTD,
    "server_session_id"         VARCHAR(255)     ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_torrelabs_discovery_search_performance_1 IS 'iglu:com.torrelabs/DiscoverySearchPerformance/jsonschema/1-0-0';
