-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.8.0
-- Generated: 2022-04-20 21:20 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_torrelabs_match_distributed_3 (
    "schema_vendor"         VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_name"           VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_format"         VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_version"        VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "root_id"               CHAR(36)         ENCODE RAW       NOT NULL,
    "root_tstamp"           TIMESTAMP        ENCODE ZSTD      NOT NULL,
    "ref_root"              VARCHAR(255)     ENCODE ZSTD      NOT NULL,
    "ref_tree"              VARCHAR(1500)    ENCODE ZSTD      NOT NULL,
    "ref_parent"            VARCHAR(255)     ENCODE ZSTD      NOT NULL,
    "feature_flag"          VARCHAR(100)     ENCODE ZSTD,
    "job_to_person_score"   DOUBLE PRECISION ENCODE RAW,
    "method"                VARCHAR(50)      ENCODE ZSTD,
    "model"                 VARCHAR(1000)    ENCODE ZSTD,
    "opportunity_crawled"   BOOLEAN          ENCODE RUNLENGTH,
    "opportunity_external"  BOOLEAN          ENCODE RUNLENGTH,
    "opportunity_locations" VARCHAR(1000)    ENCODE ZSTD,
    "opportunity_market"    VARCHAR(1000)    ENCODE ZSTD,
    "opportunity_ref"       VARCHAR(1000)    ENCODE ZSTD,
    "opportunity_remote"    BOOLEAN          ENCODE RUNLENGTH,
    "opportunity_type"      VARCHAR(1000)    ENCODE ZSTD,
    "provider"              VARCHAR(50)      ENCODE ZSTD,
    "seeker_experiments"    VARCHAR(1000)    ENCODE ZSTD,
    "subject_id"            VARCHAR(100)     ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_torrelabs_match_distributed_3 IS 'iglu:com.torrelabs/match_distributed/jsonschema/3-0-0';
