-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.8.0
-- Generated: 2022-05-24 03:48 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_torrelabs_opportunity_context_2 (
    "schema_vendor"            VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "schema_name"              VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "schema_format"            VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "schema_version"           VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "root_id"                  CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"              TIMESTAMP     ENCODE ZSTD      NOT NULL,
    "ref_root"                 VARCHAR(255)  ENCODE ZSTD      NOT NULL,
    "ref_tree"                 VARCHAR(1500) ENCODE ZSTD      NOT NULL,
    "ref_parent"               VARCHAR(255)  ENCODE ZSTD      NOT NULL,
    "id"                       VARCHAR(20)   ENCODE ZSTD      NOT NULL,
    "compensation_value"       VARCHAR(100)  ENCODE ZSTD,
    "compensation_visible"     BOOLEAN       ENCODE RUNLENGTH,
    "completion"               VARCHAR(10)   ENCODE ZSTD,
    "crawled"                  BOOLEAN       ENCODE RUNLENGTH,
    "created"                  VARCHAR(50)   ENCODE ZSTD,
    "deadline"                 VARCHAR(50)   ENCODE ZSTD,
    "external_application_url" VARCHAR(4000) ENCODE ZSTD,
    "external_info_source_url" VARCHAR(4000) ENCODE ZSTD,
    "locale"                   VARCHAR(400)  ENCODE ZSTD,
    "objective"                VARCHAR(500)  ENCODE ZSTD,
    "opportunity"              VARCHAR(500)  ENCODE ZSTD,
    "owner_gg_id"              VARCHAR(10)   ENCODE ZSTD,
    "periodicity"              VARCHAR(50)   ENCODE ZSTD,
    "stable_on"                VARCHAR(50)   ENCODE ZSTD,
    "status"                   VARCHAR(50)   ENCODE ZSTD,
    "theme"                    VARCHAR(50)   ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_torrelabs_opportunity_context_2 IS 'iglu:com.torrelabs/OpportunityContext/jsonschema/2-0-0';

ALTER TABLE atomic.com_torrelabs_opportunity_context_2 OWNER TO storageloadersnowcat;
