-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.8.0
-- Generated: 2022-04-29 15:43 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_torrelabs_solar_parse_1 (
    "schema_vendor"  VARCHAR(128)  ENCODE ZSTD    NOT NULL,
    "schema_name"    VARCHAR(128)  ENCODE ZSTD    NOT NULL,
    "schema_format"  VARCHAR(128)  ENCODE ZSTD    NOT NULL,
    "schema_version" VARCHAR(128)  ENCODE ZSTD    NOT NULL,
    "root_id"        CHAR(36)      ENCODE RAW     NOT NULL,
    "root_tstamp"    TIMESTAMP     ENCODE ZSTD    NOT NULL,
    "ref_root"       VARCHAR(255)  ENCODE ZSTD    NOT NULL,
    "ref_tree"       VARCHAR(1500) ENCODE ZSTD    NOT NULL,
    "ref_parent"     VARCHAR(255)  ENCODE ZSTD    NOT NULL,
    "type_of_record" VARCHAR(10)   ENCODE TEXT255 NOT NULL,
    "import_group"   VARCHAR(40)   ENCODE ZSTD,
    "parse_tool"     VARCHAR(7)    ENCODE TEXT255,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_torrelabs_solar_parse_1 IS 'iglu:com.torrelabs/SolarParse/jsonschema/1-0-0';

ALTER TABLE atomic.com_torrelabs_solar_parse_1 OWNER TO storageloadersnowcat;
