-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.10.0
-- Generated: 2022-07-13 14:26 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_torrelabs_team_item_added_1 (
    "schema_vendor"      VARCHAR(128)   ENCODE ZSTD      NOT NULL,
    "schema_name"        VARCHAR(128)   ENCODE ZSTD      NOT NULL,
    "schema_format"      VARCHAR(128)   ENCODE ZSTD      NOT NULL,
    "schema_version"     VARCHAR(128)   ENCODE ZSTD      NOT NULL,
    "root_id"            CHAR(36)       ENCODE RAW       NOT NULL,
    "root_tstamp"        TIMESTAMP      ENCODE ZSTD      NOT NULL,
    "ref_root"           VARCHAR(255)   ENCODE ZSTD      NOT NULL,
    "ref_tree"           VARCHAR(1500)  ENCODE ZSTD      NOT NULL,
    "ref_parent"         VARCHAR(255)   ENCODE ZSTD      NOT NULL,
    "amount"             INT            ENCODE ZSTD      NOT NULL,
    "item_type"          VARCHAR(10000) ENCODE ZSTD      NOT NULL,
    "context_page_title" VARCHAR(10000) ENCODE ZSTD,
    "email"              VARCHAR(10000) ENCODE ZSTD,
    "event_name"         VARCHAR(10000) ENCODE ZSTD,
    "href"               VARCHAR(10000) ENCODE ZSTD,
    "is_mobile"          BOOLEAN        ENCODE RUNLENGTH,
    "is_tester"          BOOLEAN        ENCODE RUNLENGTH,
    "item_description"   VARCHAR(10000) ENCODE ZSTD,
    "origin"             VARCHAR(10000) ENCODE ZSTD,
    "pathname"           VARCHAR(10000) ENCODE ZSTD,
    "port"               VARCHAR(10000) ENCODE ZSTD,
    "protocol"           VARCHAR(10000) ENCODE ZSTD,
    "public_id"          VARCHAR(10000) ENCODE ZSTD,
    "search"             VARCHAR(10000) ENCODE ZSTD,
    "send_at"            VARCHAR(10000) ENCODE ZSTD,
    "subject_id"         INT            ENCODE ZSTD,
    "user_agent"         VARCHAR(10000) ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_torrelabs_team_item_added_1 IS 'iglu:com.torrelabs/TeamItemAdded/jsonschema/1-0-0';

ALTER TABLE atomic.com_torrelabs_team_item_added_1 OWNER TO storageloadersnowcat;
